### ISSUE TITLE
Code examples outdated or not complete

### ISSUE THREAD

**Issue by sebastinez** [rnsdomains/rnsdomains.github.io#29]
Reading the architecture section of the documentation I encountered some outdated web3 code and unhandled promises.

For example:
```
var registrarInstance = web3.eth.contract(registrarAbi)
 var registrar = registrarInstance.at(registrarAddress)
```
in web3 1.2.2 should be written as:
```
const registrarInstance = new web3.eth.Contract(registrarAbi, registrarAddress)
```
`var sha3 = web3.sha3(label)` should be `const sha3 = web3.utils.sha3(label)`

And the contract methods should invoke the call or send method, and to avoid unhandled promises there should be a async/await or a .then().catch()

For example:
```
const status = registrar.entries(sha3)
```
should be 
```
const status = await registrar.methods.entries(sha3).call()
// or 
registrar.methods.entries(sha3).call().then(status => { }).catch(error => { })
```
Please let me know if you agree with this points, I would like to make a PR handling this issue.

Cheers

**Comment by ilanolkies** [comment]
Thanks! We are working to improve this type of examples.
We moved this repo to github.com/rsksmart/rsksmart.github.io. I will move the issue.
